services:
  postgres:
    image: postgres:13.3
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always